---

services:
  zsdk:
    build: .
    container_name: zsdk
    hostname: zsdk
    restart: "no"
    entrypoint: ["python"]
    volumes:
      - ./:/app
    platform: linux/amd64
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
