name: Run pytest and black format code

on:
  push:
    branches: [ main ]

jobs:
  format_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest

    - name: Run Black
      run: black .

    - name: Run pytest
      run: pytest tests/zia/

    - name: Commit and push if it changed 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (echo 'Committing changes...' && git commit -m 'Apply changes and Black formatting' && git push)
